baseURL = "https://maheenwaris.com"
title = "Maheen Waris"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "Maheen Waris"
  description = "Being a tech enthusiast, exploring the latest advancements in the digital world."
  avatarURL = "/images/Header.png"
  AvatarAltText = "avatar"
  avatarSize = "size-m"
  ShowBackToTopButton = true # true or false for "back to top" button on posts
  socialIcons = [
    {name = "twitter", url = "https://www.twitter.com/mahmil219"},
    {name = "linkedin", url = "https://www.linkedin.com/in/maheenwaris/"},
    {name = "github", url = "https://github.com/maheenwaris"},
    {name = "email", url = "mahmil219@gmail.com"}
  ]
  metaKeywords = ["blog", "maheenwaris", "hugo", "website development" ,]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/maheenwaris"
    weight = 5

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
