baseURL: "https://maheenwaris.pages.dev"
languageCode: "en-us"
title: "Maheen Waris"
theme: hugo-profile

canonifyURLs: true

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true


markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Maheen Waris"
  # description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/Home/Logo.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "dark"

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto  #Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Maheen Waris"
    subtitle: "Being a tech enthusiast, exploring the latest advancements in the digital world."
    content: "I'm a skilled frontend developer who transforms ideas into stunning digital realities. With a passion for crafting seamless user experiences, I'm here to bring your web projects to life!"
    image: /Home/Header.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    # button:
    #   enable: true
    #   name: "Resume"
    #   url: "#"
    #   download: true
    #   newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/maheenwaris
        
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/maheenwaris/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/Home/Header.png"
    content: |-
      I am a seasoned professional in frontend web development, boasting a wealth of experience in crafting visually appealing and user-friendly websites. My passion for technology extends beyond the frontend, as I am actively engaged in expanding my skill set in the realms of cybersecurity and Linux. This dual focus not only allows me to create captivating web interfaces but also ensures the security and stability of the digital environments I work on.

    # skills:
    #   enable: true
    #   title: "My toolkit includes:"
    #   items:
    #     - "🖌️ HTML"
    #     - "🎨 CSS"
    #     - "✨ JavaScript"
    #     - "🅱 Bootstrap"

  # Experience
  experience:
    enable: true
    # title: "Hepton.uk"
    items:
      - job: "Junior Web Developer"
        company: "Hepton"
        companyUrl: "https://hepton.uk"
        date: "May 2023 - present"
        content: "I've crafted professional portfolios that elegantly showcase a range of projects and accomplishments, painting a vivid picture of my journey. My expertise extends to crafting educational websites that elevate the online learning experience, enriching how knowledge is acquired. Moreover, I've masterminded the design and optimization of websites, orchestrating seamless user interactions while enhancing overall functionality."

      - job: "Intern as a Front-End Web Developer"
        company: "C-Soft Systems"
        companyUrl: "https://career.edu.pk"
        date: "October 2022 - January 2023"
        content: "During this Internship, I had the opportunity to work with a talented team of professionals and gain valuable experience in the industry. The knowledge and skills I've acquired will undoubtedly help me in my future career endeavors."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:

      - title: "NDG Linux Essentials"
        school:
          name: "Cisco Networking Academy"
          url: "https://www.netacad.com/"
        date: "August 2023"
        content: |- 
            - I take immense pride in successfully completing the NDG Linux Essentials course. It represents a significant milestone in my learning journey.
            - With the course completion comes the Linux Essentials certification, a tangible testament to my dedication and the new skills I've acquired. 
            - Having finished this course, I now possess a solid foundation in Linux, enabling me to confidently navigate and utilize this operating system.
            - Armed with this certification, I am well-prepared to take on new challenges in the IT field. It has expanded my career opportunities and prospects.
            - This accomplishment signifies my commitment to continuous learning and growth. I am excited to apply my Linux knowledge in practical settings and further advance my expertise in the future.

      - title: "Cyber Security"
        school:
          name: "Hepton.uk"
          url: "https://hepton.uk/"
        date: "June 2023 - September 2023"
        content: |- 
            - Expanded knowledge in the fields of cyber security, ethical hacking, and networking, through self-study and practical experience.
            - Explored TryHackMe platform to further enhance skills and knowledge in a collaborative and enjoyable manner, working alongside peers.
            - Actively engaged in hands-on exercises and challenges, gaining valuable experience in real world scenarios.

      - title: "Cyber Security"
        school:
          name: "Corvit System, Faisalabad"
          url: "http://www.corvitfsd.com/"
        date: "May 2023 - September 2023"
        content: |- 
            - Proficient in Linux operating system, with a strong understanding of its commands and functionalities.
            - Skilled in conducting network vulnerability scans, identifying potential weaknesses and security gaps.
            - Experienced in using various tools such as Nmap, Cupp, and IP Advancer to enhance network security and perform advanced network analysis.
            - Continuously learning and staying updated with the latest tools and techniques in the field of network security and vulnerability assessment.
            - Proficiency in Linux, combined with a knack for identifying vulnerabilities and using specialized tools, allows me to proactively address security concerns. I'm adept at not only recognizing issues but also implementing effective solutions to fortify network security and minimize risks.

      - title: "Web Development"
        school:
          name: "Career institute, Faisalabad"
          url: "https://career.edu.pk/"
        date: "March 2022 - September 2022"
        content: |-
            - I've successfully completed a variety of projects, including:
            - created custom forms to collect data efficiently.
            - designed captivating digital portfolios for individuals and businesses.
            - crafted user-friendly websites for showcasing properties.
            - developed professional websites for various industries.
            - built interactive platforms for seamless learning.
            - designed inviting sites for dining and takeout.

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: mahmil219@gmail.com
    btnName: Email me


  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"